[package]
name = "custom-dispatcher"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.1"
futures = "0.3.24"
lazy_static = "1.4.0"
serde = { version = "1.0.114", features = ["derive"] }
tokio = { version = "0.2", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }